name: Deploy to Production environment
run-name: ${{ github.actor }}'s changes are being deployed in Production environment ðŸš€

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  MAIN_BRANCH: main
  REGISTRY: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -f devops/production/Dockerfile \
            -t ghcr.io/${{ github.repository }}/main:latest \
            . --no-cache

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/main:latest

  pull-deploy:
    needs: build-push
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure latest Production branch
        run: |
          git fetch origin ${{ env.MAIN_BRANCH }}
          git checkout ${{ env.MAIN_BRANCH }}
          git pull origin ${{ env.MAIN_BRANCH }}

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.2
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Copy docker-compose to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_IP }} "mkdir -p /tmp/ci-cd-deploy"

          scp -o StrictHostKeyChecking=no \
            ./devops/production/docker-compose.yml \
            ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_IP }}:/tmp/ci-cd-deploy/docker-compose.yml

      - name: Deploy on Production server
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_IP }} << 'EOF'
              set -e
              sudo mv /tmp/ci-cd-deploy/docker-compose.yml ${{ secrets.PROD_PRJ_PATH }}/docker-compose.yml
              sudo docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
              sudo docker pull ghcr.io/${{ github.repository }}/main:latest
              sudo docker compose -f ${{ secrets.PROD_PRJ_PATH }}/docker-compose.yml \
                up -d --build --force-recreate
          EOF
